language: node_js
node_js:
    - "0.12"
addons:
  postgresql: "9.1"
script:
  - npm test
  - npm run linter
before_script:
  - psql -c 'create database timesync;' -U postgres
  - npm run migrations
git:
    submodules: false
env:
- PG_CONNECTION_STRING=postgres://postgres@localhost:5432/timesync
